# SPDX-License-Identifier: MIT
"""Persistent storage interface (CRUD for domain models)."""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from core.domain.models import (
    AuditLog,
    AutomationJob,
    Platform,
    Script,
    SSHKey,
    TaskRun,
    User,
)


class Storage(Protocol):
    # ── Users ──────────────────────────────────────────────────────────────
    def get_user_by_id(self, user_id: str) -> Optional[User]: ...
    def get_user_by_username(self, username: str) -> Optional[User]: ...
    def list_users(self, limit: int = 50, offset: int = 0) -> List[User]: ...
    def count_users(self) -> int: ...
    def create_user(self, **fields: Any) -> User: ...
    def update_user(self, user_id: str, **fields: Any) -> Optional[User]: ...
    def delete_user(self, user_id: str) -> bool: ...

    # ── SSH Keys ───────────────────────────────────────────────────────────
    def get_key_by_id(self, key_id: str) -> Optional[SSHKey]: ...
    def list_keys(self, limit: int = 50, offset: int = 0) -> List[SSHKey]: ...
    def count_keys(self) -> int: ...
    def create_key(self, **fields: Any) -> SSHKey: ...
    def delete_key(self, key_id: str) -> bool: ...

    # ── Platforms ──────────────────────────────────────────────────────────
    def get_platform_by_id(self, platform_id: str) -> Optional[Platform]: ...
    def list_platforms(self, limit: int = 50, offset: int = 0) -> List[Platform]: ...
    def count_platforms(self) -> int: ...
    def create_platform(self, **fields: Any) -> Platform: ...
    def update_platform(self, platform_id: str, **fields: Any) -> Optional[Platform]: ...
    def delete_platform(self, platform_id: str) -> bool: ...

    # ── Task Runs ──────────────────────────────────────────────────────────
    def get_task_run_by_id(self, task_run_id: str) -> Optional[TaskRun]: ...
    def list_task_runs(
        self,
        platform_id: Optional[str] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> List[TaskRun]: ...
    def count_task_runs(self, platform_id: Optional[str] = None) -> int: ...
    def create_task_run(self, **fields: Any) -> TaskRun: ...
    def update_task_run(self, task_run_id: str, **fields: Any) -> Optional[TaskRun]: ...

    # ── Scripts ────────────────────────────────────────────────────────────
    def get_script_by_id(self, script_id: str) -> Optional[Script]: ...
    def list_scripts(self, limit: int = 50, offset: int = 0) -> List[Script]: ...
    def count_scripts(self) -> int: ...
    def create_script(self, **fields: Any) -> Script: ...
    def update_script(self, script_id: str, **fields: Any) -> Optional[Script]: ...
    def delete_script(self, script_id: str) -> bool: ...

    # ── Automation Jobs ────────────────────────────────────────────────────
    def get_automation_by_id(self, automation_id: str) -> Optional[AutomationJob]: ...
    def list_automations(self, limit: int = 50, offset: int = 0) -> List[AutomationJob]: ...
    def count_automations(self) -> int: ...
    def create_automation(self, **fields: Any) -> AutomationJob: ...
    def update_automation(self, automation_id: str, **fields: Any) -> Optional[AutomationJob]: ...
    def delete_automation(self, automation_id: str) -> bool: ...

    # ── Audit Logs ─────────────────────────────────────────────────────────
    def create_audit_log(self, **fields: Any) -> AuditLog: ...
    def list_audit_logs(
        self,
        object_type: Optional[str] = None,
        user: Optional[str] = None,
        limit: int = 50,
        offset: int = 0,
    ) -> List[AuditLog]: ...
    def count_audit_logs(
        self,
        object_type: Optional[str] = None,
        user: Optional[str] = None,
    ) -> int: ...
